cart/urls.py
from . import views

from django.urls import path
urlpatterns = [
    path('cart/',views.cart,name='cart'),
    path('add_cart/<int:product_id>',views.add_cart,name='add_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('payment/',views.payement,name='payements'),
    path('order_complete/',views.order_complete,name='order_complete'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>',views.remove_cart_item,name='remove_cart_item'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>',views.remove_item,name='remove_item'),


]

cosmetic/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include,re_path
from django.conf import settings
from store.views import custom_404_view
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('account.urls')),
    path('',include('products.urls')),
    path('admin-access/',include('adminapp.urls')),
    path('review/',include('review.urls')),
    path('',include('cart.urls')),
    re_path(r'^.*$', custom_404_view),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

from account.models import Account
from django.db import models
from account.models import Account
from store.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250 ,blank=True)
    dated_added=models.DateField(auto_now_add=True)



    def __str__(self):
        return self.cart_id


class Cartitem(models.Model):
    user=models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    quantity=models.IntegerField()

    is_active=models.BooleanField(default=True)

    def subtotal(self):
        return self.product.price*self.quantity

    def __str__(self):
        return str(self.product)



# Create your models here.

class Payment (models.Model):
    user =models.ForeignKey(Account,on_delete=models.CASCADE)
    payment_id=models.CharField(max_length=100)
    payment_method=models.CharField(max_length=100) #paypayel
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    status=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.payment_id



class Order(models.Model):
    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )
    user =models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    payment =models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    order_number=models.CharField(max_length=20)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    phone=models.CharField(max_length=20)
    company=models.CharField(max_length=30,blank=True,null=True)
    email=models.EmailField(max_length=50,blank=True,null=True)
    address_line_1=models.CharField(max_length=100)
    address_line_2=models.CharField(max_length=100,blank=True,null=True)
    country=models.CharField(max_length=50)
    postal_code=models.CharField(max_length=10,blank=True,null=True)
    state=models.CharField(max_length=50,blank=True,null=True)
    city=models.CharField(max_length=20)
    total=models.FloatField()
    tax=models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip=models.CharField(max_length=20,blank=True)
    order_note=models.TextField(max_length=100,blank=True)
    is_ordered =models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    

    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    
        

    def __str__(self):
        return self.first_name


class Order_Product(models.Model):
    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('Cancelled','Cancelled'),
    )
    status=models.CharField(max_length=10,choices=STATUS,default='New')

    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    payment =models.ForeignKey(Payment,on_delete=models.SET_NULL,null=True,blank=True)
    user =models.ForeignKey(Account,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    product_price=models.FloatField()
    is_ordered=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.product.product_name


class Personalization(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cartitem,on_delete=models.SET_NULL,null=True)
    order=models.ForeignKey(Order_Product,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=100)
    buyed=models.BooleanField(default=False)

    def __str__(self):
        return self.message  

templates/owner/add-item.html
{% extends 'owner/base.html' %}
{% load static %}
{% block content %}
	<!-- main content -->
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>Add Products</h2>
					</div>
				</div>
				<!-- end main title -->

				<!-- form -->
				<div class="col-12">
					<form action="{% url 'add_item' %}" method='POST' enctype="multipart/form-data" class="form">
						
						 {% csrf_token %}
						<div class="row">
							{% include '../includes/alert.html' %}
							<div class="col-12 col-md-5 form__cover">
								<div class="row">
									<div class="col-12 col-sm-6 col-md-12">
										<div class="form__img">
											<label for="form__img-upload">Upload product photo (190 x 270)</label>
											<input type="file" id="form__img-upload" required name="form__img-upload" type="file" accept=".png, .jpg, .jpeg"> <img id="form__img" src="#" alt=" ">
										</div>
									</div>
								</div>
							</div>

							<div class="col-12 col-md-7 form__content">
								<div class="row">
									<div class="col-12 col-sm-6">
										<div class="form__group">
											<input type="text" required class="form__input" name='product_name' placeholder="Product name">
										</div>
									</div>
									<div class="col-12 col-sm-6">
										<div class="form__group">
											<input type="text" required class="form__input" name='price' placeholder="Price">
										</div>
									</div>
									

									<div class="col-12">
										<div class="form__group">
											<textarea id="text" required name="descriptions" class="form__textarea"  placeholder="Descriptions "></textarea>
										</div>
									</div>
									<div class="col-12">
										<div class="form__group">
											<textarea id="text" name="details" class="form__textarea" placeholder="Details"></textarea>
										</div>
									</div>

									

 
								
	
									<div class="col-12 ">
										<div class="form__group">
											<select class="js-example-basic-multiple" name='category' id="genre_en" multiple="multiple" placeholder='choose category'>
												{% for collection in collections %}
												<option value="{{collection.id}}">{{collection.collection}}</option>
												{% endfor %}
											</select>
										</div>
									</div> 
									
							</div>

							<div class="col-12">
								<div class="row">			
									<div class="col-12">
										<button type="submit" class="form__btn">Add Product</button>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
				<!-- end form -->
			</div>
		</div>
	</main>
	<!-- end main content -->
{% endblock %}

templates/owner/add_collection.html
{% extends 'owner/base.html' %}
{% load static %}
{% block content %}
	<!-- main content -->
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>Add Collections| Category</h2>
					</div>
				</div>
				<!-- end main title -->

				<!-- form -->
				<div class="col-12">
					<form action="{% url 'add_collection' %}" method='POST' enctype="multipart/form-data" class="form">

						 {% csrf_token %}
						<div class="row">
							{% include '../includes/alert.html' %}
                            <div class="col-12 col-md-5 form__cover">
								<div class="row">
									<div class="col-12 col-sm-6 col-md-12">
										<div class="form__img">
											<label for="form__img-upload">Upload product photo (190 x 270)</label>
											<input type="file" id="form__img-upload" required name="image" type="file" accept=".png, .jpg, .jpeg"> <img id="form__img" src="#" alt=" ">
										</div>
									</div>
								</div>
							</div>
							<div class="col-12 col-md-7 form__content">
								<div class="row">
									<div class="col-12 col-sm-6">
										<div class="form__group">
											<input type="text" required class="form__input" name='category_name' placeholder="Category">
										</div>
									</div>



									<div class="col-12">
										<div class="form__group">
											<textarea id="text" required name="descriptions" class="form__textarea"  placeholder="Descriptions "></textarea>
										</div>
									</div>

							</div>

							<div class="col-12">
								<div class="row">
									<div class="col-12">
										<button type="submit" class="form__btn">Add collection</button>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
				<!-- end form -->
			</div>
		</div>
	</main>
	<!-- end main content -->
{% endblock %}

templates/owner/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'superadmin/css/bootstrap-reboot.min.css' %}">
	<link rel="stylesheet" href="{% static 'superadmin/css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'superadmin/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'superadmin/css/select2.min.css' %}">
	<link rel="stylesheet" href="{% static 'superadmin/css/admin.css' %}">

   <title>Mapple court Admin</title>

	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="title" content="Handmade Greeting Cards | Maple Court Yard">
	<meta name="index" content="greeting cards, handmade cards, personalized cards, custom greeting cards, Maple Court Yard">
	<meta name="description" content="Discover unique, handmade greeting cards for every occasion at Maple Court Yard. Personalize your card today for a truly special touch.">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Handmade Greeting Cards - Bespoke and Personalized | Maple Court Yard">
	<meta property="og:description" content="Explore Maple Court Yard for the most personalized handmade cards for every occasion. Make your moments special with our bespoke greeting cards.">
	<meta property="og:image" content="https://maplecourtyarddesigns.co.uk/static/img/image.png"> <!-- Add an image URL for better engagement on social media -->
	<meta property="og:url" content="https://www.maplecourtyarddesigns.co.uk"> <!-- Ensure this matches your site's URL -->
	
</head>
<body>
    {% include 'owner/include/header.html' %}
    {% block content %}
    {% endblock %}

<!-- JS -->
<script src="{% static 'superadmin/js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'superadmin/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'superadmin/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'superadmin/js/smooth-scrollbar.js' %}"></script>
<script src="{% static 'superadmin/js/select2.min.js' %}"></script>
<script src="{% static 'superadmin/js/admin.js' %}"></script>
</body>
</html>

templates/owner/catalog.html
{% extends 'owner/base.html' %}
{% load static %}


{% block content %}

	<!-- main content -->
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>Catalog</h2>
						{% include '../includes/alert.html' %}
						
						<span class="main__title-stat">{{count}} total</span>
						

						<div class="main__title-wrap">
							<!-- filter sort -->
							{% comment %} <div class="filter" id="filter__sort">
								<span class="filter__item-label">Sort by:</span>

								<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<input type="button" value="Date created">
									<span></span>
								</div>

								<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">
									<li>Date created</li>
									<li>Rating</li>
									<li>Views</li>
								</ul>
							</div> {% endcomment %}
							<!-- end filter sort -->

							<!-- search -->
						

							<form style="width:500px;" method="POST" class="main__title-form">
								{% csrf_token %}
								<input name="keyword" style="margin-right:20px;" type="text" placeholder="Find Products..">
								<button style="width:100px;height:45px;border-radius:0%;" class="sign__btn" type="submit">Search</button>

							</form> 
							<!-- end search -->
						</div>
					</div>
				</div>
				<!-- end main title -->

				

				<!-- users -->
				<div class="col-12">
					<div class="main__table-wrap">
						<table class="main__table">
							<thead>
							
								<tr>
									<th>ID</th>
									<th>Product Name</th>
									<th>Product Price</th>
									<th>CRAETED DATE</th>
									<th>ACTIONS</th>
								</tr>
								
							</thead>

							<tbody>
								<tr>
									
									{% for product in products %}
									<td>
										<div class="main__table-text">{{product.id}}</div>
									</td>
									<td>
										<div class="main__table-text"><a href="#">{{product.product_name|truncatechars:30}}</a></div>
									</td>
									
									<td>
										<div class="main__table-text">{{product.price}}</div>
									</td>
									
									<td>
										<div class="main__table-text">{{product.created_date|date:"m/d/Y"}}</div>
									</td>
									<td>
										<div class="main__table-btns">
											<a href="{% url 'edit_product' product.id %}" class="main__table-btn main__table-btn--edit">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,7.24a1,1,0,0,0-.29-.71L17.47,2.29A1,1,0,0,0,16.76,2a1,1,0,0,0-.71.29L13.22,5.12h0L2.29,16.05a1,1,0,0,0-.29.71V21a1,1,0,0,0,1,1H7.24A1,1,0,0,0,8,21.71L18.87,10.78h0L21.71,8a1.19,1.19,0,0,0,.22-.33,1,1,0,0,0,0-.24.7.7,0,0,0,0-.14ZM6.83,20H4V17.17l9.93-9.93,2.83,2.83ZM18.17,8.66,15.34,5.83l1.42-1.41,2.82,2.82Z"/></svg>
											</a>
											<a href="{% url 'remove_product' product.id %}" onclick="return confirmDelete();" class="main__table-btn main__table-btn--delete ">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10,18a1,1,0,0,0,1-1V11a1,1,0,0,0-2,0v6A1,1,0,0,0,10,18ZM20,6H16V5a3,3,0,0,0-3-3H11A3,3,0,0,0,8,5V6H4A1,1,0,0,0,4,8H5V19a3,3,0,0,0,3,3h8a3,3,0,0,0,3-3V8h1a1,1,0,0,0,0-2ZM10,5a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1V6H10Zm7,14a1,1,0,0,1-1,1H8a1,1,0,0,1-1-1V8H17Zm-3-1a1,1,0,0,0,1-1V11a1,1,0,0,0-2,0v6A1,1,0,0,0,14,18Z"/></svg>
											</a>
										</div>
									</td>
								</tr>
								{% endfor %}
								</tbody>
						</table>
					</div>
				</div>
				<!-- end users -->

				<!-- paginator -->
				{% comment %} <div class="col-12">
					<div class="paginator">
						<span class="paginator__pages">10 from 14 452</span>

						<ul class="paginator__paginator">
							<li>
								<a href="#">
									<svg width="14" height="11" viewBox="0 0 14 11" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.75 5.36475L13.1992 5.36475" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M5.771 10.1271L0.749878 5.36496L5.771 0.602051" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
								</a>
							</li>
							<li class="active"><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li>
								<a href="#">
									<svg width="14" height="11" viewBox="0 0 14 11" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.1992 5.3645L0.75 5.3645" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M8.17822 0.602051L13.1993 5.36417L8.17822 10.1271" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
								</a>
							</li>
						</ul>
					</div>
				</div> {% endcomment %}
				<!-- end paginator -->
	<style>
				.active{
				background-color:#ff0000;
				padding-left:10px;
				margin-right:10px;
				margin-left:10px;
				}
				</style>
				<div class="col-12">
					<div class="paginator">
						<span class="paginator__pages">10 from {{count}}</span>

						<ul class="catalog__paginator">
							<nav class="mt-4" aria-label="Page navigation sample">
								{% if all_products.has_other_pages %}
								<ul class="pagination" style='display: flex;
								margin-bottom: 13px;'>
									{% if all_products.has_previous %}
									<li class="page-item "><a class="page-link"
											href="?page={{all_products.previous_page_number}}" style='color:white; margin-right:13px;'>Previous</a></li>
									{% else %}
									<li class="page-item disabled"><a class="page-link" style='color:white; margin-right:13px;' href="">Previous</a></li>
									{% endif %}
			
									{% for i in all_products.paginator.page_range %}
									{% if all_products.number == i %}
									<li class="page-item active" ><a class="page-link" style='color:white; margin-right:13px;'href="#">{{i}}</a></li>
									{% else %}
									<li class="page-item "><a class="page-link" style='color:white; margin-right:13px;' href="?page={{i}}">{{i}}</a></li>
									{% endif %}
									{% endfor %}
									{% if all_products.has_next %}
									<li class="page-item"><a class="page-link " href="?page={{all_products.next_page_number}}" style='color:white; margin-left:13px;'>Next</a></li>
									{% else %}
									<li class="page-item disabled"><a class="page-link" style='color:white;' href="#">Next</a></li>
									{% endif %}
								</ul>
								{% endif %}
							</nav>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</main>
	<!-- end main content -->

	<!-- modal status -->
	<div id="modal-status" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">Status change</h6>

		<p class="modal__text">Are you sure about immediately change status?</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">Apply</button>
			<button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
		</div>
	</div>
	<!-- end modal status -->

	<!-- modal delete -->
	<div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">Item delete</h6>

		<p class="modal__text">Are you sure to permanently delete this item?</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">Delete</button>
			<button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
		</div>
	</div>
	<!-- end modal delete -->


	<script>
		function confirmDelete() {
			return confirm("Are you sure you want to delete?");
		}
	</script>

	{% endblock %}

templates/owner/transaction.html
{% extends 'owner/base.html' %}

{% load static %}

{% block content %}
	<!-- end sidebar -->

	<!-- main content -->
	<main class="main">
		<div class="container-fluid">
			<div class="row">
				<!-- main title -->
				<div class="col-12">
					<div class="main__title">
						<h2>User Transactions</h2>
						{% with item_count=payments|length %}
						<span class="main__title-stat">{{item_count}} total Transactions</span>
						{% endwith %}

						<div class="main__title-wrap">
							<!-- filter sort -->
							<div class="filter" id="filter__sort">
								<span class="filter__item-label">Analytics:</span>

								<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<input type="button" value="Based on">
									<span></span>
								</div>

								<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">
									<li ><a style="color:white" href="{% url 'transactions' %}">Users</a></li>
									<li><a style="color:white;" href="{% url 'transactions_country' %}">Country</a></li>
									<li><a style="color:white;" href="{% url 'transactions_product' %}">Product</a></li>
								</ul>
							</div> 
							<!-- end filter sort -->

							<!-- search -->
							<form style="width:400px;" method="post" class="main__title-form" >
								{% csrf_token %}
								<select style="background-color:#151f30;padding:10px;color:white;border-radius:10%;" class="custom-select dropdown-menu scrollbar-dropdown" name="time_range">
									<option value="1_week" {% if selected_time_range == "1_week" %}selected{% endif %}>This Week</option>

									<option value="1_month" {% if selected_time_range == "1_month" %}selected{% endif %}>This Month</option>
									<option value="2_months" {% if selected_time_range == "2_months" %}selected{% endif %}>Before 2 months</option>

									<option value="3_months" {% if selected_time_range == "3_months" %}selected{% endif %}>Before 3 months</option>
									<option value="6_months" {% if selected_time_range == "6_months" %}selected{% endif %}>Before 6 months</option>
								</select>
								<select style="margin-left:20px;background-color:#151f30;padding:10px;color:white;border-radius:10%;" class="custom-select dropdown-menu scrollbar-dropdown" name="item_count">
									<option value="20" {% if selected_item_count == "20" %}selected{% endif %}>20 Items</option>
									<option value="40" {% if selected_item_count == "40" %}selected{% endif %}>40 Items</option>
									<option value="60" {% if selected_item_count == "60" %}selected{% endif %}>60 Items</option>
									<option value="80" {% if selected_item_count == "100" %}selected{% endif %}>100 Items</option>	
								</select>
								<button style="width:100px;height:45px;border-radius:0%;" class="sign__btn" type="submit">Filter</button>
							</form>
							{% comment %} <form action="#" class="main__title-form">
								<input type="text" placeholder="Find user..">
								<button type="button">
									<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="8.25998" cy="8.25995" r="7.48191" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></circle><path d="M13.4637 13.8523L16.3971 16.778" stroke="#2F80ED" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
								</button>
							</form> {% endcomment %}
							<!-- end search -->
						</div>
					</div>
				</div>
				<!-- end main title -->

				<!-- users -->
				<div class="col-12">
					<div  class="main__table-wrap">
						<table class="main__table">
							<thead>
								<tr>
									<th>ID</th>
									<th>USERNAME</th>
									<th>Money Spent</th>
									<th>Items</th>

									<th>Payment Method</th>
									<th>CREATED DATE</th>
								</tr>
							</thead>

							<tbody>
								{% for payment in payments %}
								<tr>
									<td>
										<div class="main__table-text">{{payment.id}}</div>
									</td>
									<td>
										<div class="main__user">
											<div class="main__avatar">
												<img src="img/user.svg" alt="">
											</div>
											<div class="main__meta">
												<span>{{payment.user.email}}</span>
											</div>
										</div>
									</td>
									
									<td>
										
										<div class="main__table-text">{{payment.amount_paid|floatformat:2}} $</div>
										
									</td>
									<td>
										
										<div class="main__table-text">
											 <div class="filter" id="filter__sort">
				
												<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<input type="button" value="Movies Bought">
													<span></span>
												</div>
				
												<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">
													{% for order_product in payment.order_product_set.all %}
															<li>{{ order_product.product }} ( {{order_product.product_price}} $)</li>
												{% endfor %}
												{% for order_product in payment.order_product_album_set.all %}
															<li>{{ order_product.product.album }} ( {{order_product.product_price}} $)</li>
												{% endfor %}

												</ul>
											</div> 
										</div>
										
									</td>
									<td>
										<div class="main__table-text">{{payment.payment_method}}</div>
									</td>
									<td>
										<div class="main__table-text">{{payment.created_at|date:"Y-m-d"}}</div>
									</td>
									
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					
				</div>
				</div>
				<!-- end users -->

				<!-- paginator -->
				<div class="col-12">
					<div class="paginator">
						{% with item_count=payments|length %}
						<span class="paginator__pages">10 from {{item_count}}</span>
						{% endwith %}
						<ul class="catalog__paginator">
							<nav class="mt-4" aria-label="Page navigation sample">
								{% if all_products.has_other_pages %}
								<ul class="pagination" style='display: flex;
								margin-bottom: 13px;'>
									{% if all_products.has_previous %}
									<li class="page-item "><a class="page-link"
											href="?page={{all_products.previous_page_number}}" style='color:white; margin-right:13px;'>Previous</a></li>
									{% else %}
									<li class="page-item disabled"><a class="page-link" style='color:white; margin-right:13px;' href="">Previous</a></li>
									{% endif %}
			
									{% for i in all_products.paginator.page_range %}
									{% if all_products.number == i %}
									<li class="page-item active" ><a class="page-link" style='color:white; margin-right:13px;'href="#">{{i}}</a></li>
									{% else %}
									<li class="page-item "><a class="page-link" style='color:white; margin-right:13px;' href="?page={{i}}">{{i}}</a></li>
									{% endif %}
									{% endfor %}
									{% if all_products.has_next %}
									<li class="page-item"><a class="page-link active" href="?page={{all_products.next_page_number}}" style='color:white; margin-left:13px;'>Next</a></li>
									{% else %}
									<li class="page-item disabled"><a class="page-link" style='color:white;' href="#">Next</a></li>
									{% endif %}
								</ul>
								{% endif %}
							</nav>
						</ul>
					</div>
				</div>
			
				<!-- end paginator -->
			</div>
		</div>
	</main>
	<!-- end main content -->

	<!-- modal status -->
	<div id="modal-status" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">Status change</h6>

		<p class="modal__text">Are you sure about immediately change status?</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">Apply</button>
			<button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
		</div>
	</div>
	<!-- end modal status -->

	<!-- modal delete -->
	<div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
		<h6 class="modal__title">User delete</h6>

		<p class="modal__text">Are you sure to permanently delete this user?</p>

		<div class="modal__btns">
			<button class="modal__btn modal__btn--apply" type="button">Delete</button>
			<button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
		</div>
	</div>
	<!-- end modal delete -->
{% endblock %}